### ISSUE TITLE
Add logging to server code and setup/teardown scripts

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/eligibility-server#108]
We should configure logging for the project as a whole and add relevant statements throughout the code.

### Additional context
> Maybe a follow-up: figure out how to get the Python `logging` framework configured and replace the `print` statements with more appropriate log-level statements.

_Originally posted by @thekaveman in https://github.com/cal-itp/eligibility-server/pull/104#pullrequestreview-1061063341_

**Comment by thekaveman** [comment]
Thanks for creating this issue @angela-tran. 

Maybe we expand the scope a bit to configure logging for this project as a whole, and add some relevant statements throughout the code.

**Comment by angela-tran** [comment]
@thekaveman Good idea! I'm not sure where this should go, so I put it in the project Backlog status. Feel free to move it though if it should be somewhere else!

**Comment by thekaveman** [comment]
See also: [Flask Logging](https://flask.palletsprojects.com/en/2.2.0/logging/)
