### ISSUE TITLE
Use Flask configuration framework to load settings

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/eligibility-server#109]
Instead of getting config manually from the `settings` module like:

```python
app = Flask(__name__)
app.name = settings.APP_NAME
app.config["SQLALCHEMY_DATABASE_URI"] = settings.SQLALCHEMY_DATABASE_URI
# etc.
```

Flask has built-in support for loading the configuration from a number of sources. We're using the [Python files format](https://flask.palletsprojects.com/en/2.2.x/config/#configuring-from-python-files), which would look something like:

```python
app = Flask(__name__)
app.config.from_object("eligibility_server.settings")
```

We can also load from a number of [supported file types](https://flask.palletsprojects.com/en/2.2.x/config/#configuring-from-data-files):

```python
import json
app.config.from_file("config.json", load=json.load)
```

Or directly from certain [environment variables](https://flask.palletsprojects.com/en/2.2.x/config/#configuring-from-environment-variables):

```python
app.config.from_prefixed_env()
```

Let's use the built-in framework for loading configuration data.

See also: [Flask Configuration Best Practices](https://flask.palletsprojects.com/en/2.2.x/config/#configuration-best-practices)

**Comment by machikoyasuda** [comment]
https://flask.palletsprojects.com/en/2.2.x/config/#configuring-from-python-files

**Comment by machikoyasuda** [comment]
https://flask.palletsprojects.com/en/2.2.x/config/#configuration-best-practices
