### ISSUE TITLE
Handle application errors

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/eligibility-server#110]
See [Flask - Handling Application Errors](https://flask.palletsprojects.com/en/2.2.x/errorhandling/#handling-application-errors)

Specifically, we should look at [Returning API Errors as JSON](https://flask.palletsprojects.com/en/2.2.x/errorhandling/#returning-api-errors-as-json).

* `403` (forbidden, not authenticated/authorized)
* `404` (endpoint not found)
* `500` (other application error / Exception)

**Comment by machikoyasuda** [comment]
https://flask.palletsprojects.com/en/2.2.x/errorhandling/#returning-api-errors-as-json
