### ISSUE TITLE
Make test data match the schema necessary for next release

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/eligibility-server#114]
We should make the CSV and JSON data test files match the schema we need for future releases

**Comment by thekaveman** [comment]
I suggest we make 2 tables:

## `user`

Existing, but modified:

| Column | Type | Description |
|----------|------|--------------|
| `id`        | `int` | Autogenerated PK |
| `user_id` | `str` | Imported user id |
| `user_name` | `str` | Imported user name |

## `eligibility`

New:

| Column | Type | Description |
|----------|------|--------------|
| `id`        | `int` | Autogenerated PK |
| `user_id` | `int` | Reference to `user.id` |
| `type` | `str` | Name of eligibility type |

This will give us a nice way to separate loading users from the types. And it puts us on the path to having a default, server-wide type that applies to all users when the data doesn't come with types (e.g. we populate the `eligibility` table with a record for each user with the default type if configured).

Read more about model relationships:

* [`Flask-SQLAlchemy`: One-to-many Relationships](https://flask-sqlalchemy.palletsprojects.com/en/2.x/models/#one-to-many-relationships)
* [`SQLAlchemy`: Basic relationship patters > One to many](https://docs.sqlalchemy.org/en/14/orm/basic_relationships.html#one-to-many)

**Comment by thekaveman** [comment]
Closing in favor of refactor task in #122
