### ISSUE TITLE
Refactor server code into subdirectory

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/eligibility-server#12]
The `app.py` module currently sits at the root of the repository. This is fine for a single file, but can cause trouble when trying to import objects from the module (see e.g. #10) or when the code becomes more complicated than a single file.

Recommendation is to create a subdirectory, named `eligibility_server`, and place both the `app.py` and an (empty) `__init__.py` file in there.

Elsewhere (e.g. in tests) you could then:

```python
from eligibility_server import app
```

**Comment by thekaveman** [comment]
Here's some more info: https://docs.python-guide.org/writing/structure/

**Comment by machikoyasuda** [comment]
- https://github.com/cal-itp/eligibility-server/blob/main/docker-compose.yml#L17 `FLASK_APP=eligibility-server/app.py`

**Comment by thekaveman** [comment]
As part of this, you may want to bake the `FLASK_APP` environment variable into the Dockerfile. This way it is not reliant on running with Compose to inject that value. 

More on the nuance of environment variables in Dockerfiles / Docker: https://vsupalov.com/docker-arg-env-variable-guide/
