### ISSUE TITLE
Refactor database class

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/eligibility-server#122]
As we move into becoming production-ready, there are a few items of cleanup in the [`Database` class](https://github.com/cal-itp/eligibility-server/blob/main/eligibility_server/database.py) that should happen.

cc @angela-tran who discussed this with me earlier today and informed this ticket. 
cc @machikoyasuda we held off on some of this to make #116 more straightforward, documenting here instead.

| Method | Feedback |
| --------- | ----------- |
| `__init__()` | let's not query and store all users. We may have a large list of users, and don't necessarily want to hold them all in-memory |
| `__init__()` | log the given `hash` option as `DEBUG` |
| `check_user()` | break up large `if(...)` statement checking the various states into `if/elif/else` etc. |
| `check_user()` | query for the user here |
| `check_user()` | separate calculation of the return value from the `return` statement |
| `check_user()` | add various logging to the above refactors |

Let's also verify the tests are providing adequate coverage and scoping.

**Comment by thekaveman** [comment]
I suggest we make 2 tables:

## `user`

Existing, but modified:

| Column | Type | Description |
|----------|------|--------------|
| `id`        | `int` | Autogenerated PK |
| `user_id` | `str` | Imported user id |
| `user_name` | `str` | Imported user name |

## `eligibility`

New:

| Column | Type | Description |
|----------|------|--------------|
| `id`        | `int` | Autogenerated PK |
| `user_id` | `int` | Reference to `user.id` |
| `type` | `str` | Name of eligibility type |

This will give us a nice way to separate loading users from the types. And it puts us on the path to having a default, server-wide type that applies to all users when the data doesn't come with types (e.g. we populate the `eligibility` table with a record for each user with the default type if configured).

Read more about model relationships:

* [`Flask-SQLAlchemy`: One-to-many Relationships](https://flask-sqlalchemy.palletsprojects.com/en/2.x/models/#one-to-many-relationships)
* [`SQLAlchemy`: Basic relationship patters > One to many](https://docs.sqlalchemy.org/en/14/orm/basic_relationships.html#one-to-many)

**Comment by angela-tran** [comment]
I felt a little stuck / deadlocked with #130 and #131, and then I realized it would simplify things if I removed the need to hold all users in memory. Once #132 is merged in, I'll have a path forward for #131.
