### ISSUE TITLE
Duplicate CodeQL checks

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/eligibility-server#124]
I think maybe our CodeQL workflow is defined in a way that causes duplicate checks on pull requests:   

![image](https://user-images.githubusercontent.com/25497886/184172775-6ee7fd42-cc3b-4a4f-af73-5eae9d947af4.png)

**Comment by thekaveman** [comment]
It's true, we have it defined for both `on:push` and `on:pull_request:main`. 

[According to the CodeQL docs](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository#setting-up-code-scanning-using-actions), this is a best practice.

> In the default CodeQL analysis workflow, code scanning is configured to analyze your code each time you either push a change to the default branch or any protected branches, or raise a pull request against the default branch. As a result, code scanning will now commence.
>
> The `on:pull_request` and `on:push` triggers for code scanning are each useful for different purposes.

Read more about [Scanning PRs](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#scanning-pull-requests) and [Scanning pushes](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#scanning-on-push)
