### ISSUE TITLE
Make it easier for tests to use a separate app and database

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/eligibility-server#131]
This is related to #130 (and its original ticket #122).

I am trying to write tests that cover the cases mentioned in #105:

**<details><summary>Cases**</summary>
> ## Testing
> ### Test data
> 
>     Test JSON without hashing
>     Test JSON with hashing
>     Test CSV with default CSV configs, no hashing
>     Test CSV with custom CSV configs, no hashing
>     Test CSV with custom CSV configs, with hashing
> 
> ### Test scenarios
> 
>     Test a JSON without any hashing
>     Test a JSON with sha256
>     Test a JSON with sha512
>     Test a CSV without any hashing, without any special CSV configs / only default CSV configs
>     Test a CSV with sha256
>     Test a CSV with sha512
>     Test a CSV with custom configs: custom delimiter
>     Test a CSV with custom configs: custom quote characters
>     Test a CSV with custom configs: custom delimiter, and hashing with sha256
>     Test a CSV with custom configs: custom quote characters, and hashing with sha256
</details>

I'm having difficulty writing a test for the `setup` module since it directly imports the `app` object from `eligibility_server.app`. My [attempt](https://github.com/cal-itp/eligibility-server/pull/130/commits/bfc46118c726ee112b28971ac3e59caa1360d864) to patch the module's instance and configure a test database on that patch got me very close, but then I'm not able to query for `User`s or `Eligibility`s because those are defined on the `eligibility_server.app.db` instance.

I think we could do something like what the Flask documentation describes as the ["app factory"](https://flask.palletsprojects.com/en/2.2.x/patterns/appfactories/) pattern.
Some examples I found:
 - https://gitlab.com/patkennedy79/flask_user_management_example/-/blob/main/project/__init__.py#L22
 - https://github.com/rochacbruno/flask-project-template/blob/main/project_name/base.py#L5
    - [conftest.py](https://github.com/rochacbruno/flask-project-template/blob/main/tests/conftest.py#L11-L12)

Additional resources:
 - https://www.patricksoftwareblog.com/testing-a-flask-application-using-pytest/

**Comment by angela-tran** [comment]
I haven't started on this yet, but plan to start tomorrow

**Comment by thekaveman** [comment]
The ["app factory"](https://flask.palletsprojects.com/en/2.2.x/patterns/appfactories/) Flask docs start by saying:

> If you are already using packages and blueprints for your application... 

I think part of the issues you've described here are attributable to how we are not _quite_ a Flask ["application package"](https://flask.palletsprojects.com/en/2.2.x/patterns/packages/#simple-packages) (I think we can ignore Blueprints for the moment):

* Our `setup.py` does not actually install our app as a python package (e.g. we can't run `pip install -e .`)
* Our `app` Flask application object is created in a specific module (`app.py`), leading to funky statements elsewhere like `app.app.config["KEY"]` and making the imports challenging

Maybe starting with making this a true Flask "application package" would get us closer on a lot of the testing etc. issues, then moving into app factory as we want to test more and different configs?

**Comment by thekaveman** [comment]
A thought on file organization as I'm working on #135 and also thinking about this issue...

We could introduce a sub-directory/package like `eligibility_server/db` and move:

* `setup.py`
* `teardown.py`
* `database.py` (maybe rename to something... `models`? Maybe split out the checking into something else?)

 Then a "package"-level `setup.py` could be introduced at the root to address the issue above.

**Comment by angela-tran** [comment]
Unassigning from myself since I'm not currently working on this. #140 got us most of what we needed to test the database import code (see tests in #148). 

What remains to be done (and what this ticket covers) is giving the tests more flexibility in which database / app they are actually writing to.

**Comment by angela-tran** [comment]
The current set up of using our local database for testing has been working fine
