### ISSUE TITLE
Whiteboard a process for IdG providing the AUTH_TOKEN value

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/eligibility-server#160]
CDT's IdG is also an authorization server/security token service. IdG could sit between the Benefits app and the Eligibility Server, to provide access to Benefits to call the API. Based on a comment from @johnatstate on the #158 write-up.

Rough outline (may not be entirely accurate/complete):

* Benefits has a `client_id` / `client_secret` pair for an app registered with IdG for a particular `scope` (e.g. `eligibility_verification`)
* Before making an EV API call, Benefits requests an `AUTH_TOKEN` from IdG using the OIDC `client_credentials` flow (similar to how the Login.gov flow works)
* Benefits sends the IdG provided `AUTH_TOKEN` to Server with API call
* Server validates `AUTH_TOKEN` with IdG
* If valid, Server accepts Benefits API call and processes

**Comment by angela-tran** [comment]
There is some security gain to using a short-lived token, but it would take a lot of effort. We decided this is low-priority.
