### ISSUE TITLE
Deploy for MST Courtesy Cards

### ISSUE THREAD

**Issue by afeld** [cal-itp/eligibility-server#163]
_Wasn't sure if we want to track this in this repository or under [benefits](https://github.com/cal-itp/benefits/issues)._

Tracking tasks in [this doc](https://docs.google.com/document/d/1WdH75tPGYaZuqLkC4q-Uw14qde1mozchdU1clQxkQWU/edit#heading=h.cku3w2aadfcq) so that MST can contribute; we can move here instead if preferred.

The goal of this task is to have the server deploying in MST's Azure, with the Infrastructure as Code (terraform) components tracked in this repository.

**Comment by afeld** [comment]
[Holding off until week of 10/24.](https://cal-itp.slack.com/archives/C043NFXPUAG/p1665620387848079?thread_ts=1665610110.045339&cid=C043NFXPUAG)

**Comment by thekaveman** [comment]
Related, but for the next sprint: https://github.com/cal-itp/benefits/issues/1038
