### ISSUE TITLE
Setup branch protection

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/eligibility-server#18]
We want the `main` branch to be protected:

* [x] disallow deletion
* [x] disallow `git push --force` (we should merge all changes via PR)
* [x] require the `pre-commit` check to pass

Settings here: https://github.com/cal-itp/eligibility-server/settings/branches

More info: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches

**Comment by machikoyasuda** [comment]
- Disallow `git push --force` for all users:

![image](https://user-images.githubusercontent.com/3673236/136082776-b966be8d-81e8-42f5-9ef0-0855df72727e.png)
![image](https://user-images.githubusercontent.com/3673236/136082803-fd52ddb0-baaf-4ae4-851f-328005299b51.png)


- Require `pre-commit`

![image](https://user-images.githubusercontent.com/3673236/136082832-6e8b3192-376a-40fc-ac5a-ff5d20bbb4dd.png)

- And by default, protected branches cannot be deleted.

**Comment by thekaveman** [comment]
This is great! We can leave it for now, but we may want to relax _Require branches to be up to date before merging_. This can be a little bit of a pain when multiple PRs are ongoing.
