### ISSUE TITLE
downgrade App Service plan

### ISSUE THREAD

**Issue by afeld** [cal-itp/eligibility-server#200]
We are currently using the PremiumV2 plan:

https://github.com/cal-itp/eligibility-server/blob/b1c82617e97ea614d0542513ab028c7917e340b6/terraform/app_service.tf#L6

which is almost certainly more than we need, and thus a waste of money. [More details.](https://learn.microsoft.com/en-us/azure/app-service/overview-hosting-plans)

This is the case in Benefits as well; asking DevSecOps about whether it's necessary.

**Comment by angela-tran** [comment]
Maybe we should have dev and test environments use the Free or Shared plan and have prod use Basic

https://azure.microsoft.com/en-us/pricing/details/app-service/windows/#pricing

**Comment by afeld** [comment]
From Param at DevSecOps, re: using PremiumV2 for Benefits:

> We use Premium so that we get 20 instances to scale up in case needed, for all our Production environments. This also helps us create slots for lower environments in the same plan. Definitely you can go with the standard plan as we are going to have separate environments for Dev and Test. By the way standard plan gives us 10 instances which may be sufficient. Totally up to you.
