### ISSUE TITLE
restrict access to Key Vault?

### ISSUE THREAD

**Issue by afeld** [cal-itp/eligibility-server#203]
We got the following finding as part of https://github.com/cal-itp/eligibility-server/issues/196:

```
CRITICAL: Vault network ACL does not block access by default.
════════════════════════════════════════
Network ACLs allow you to reduce your exposure to risk by limiting what can access your key
vault.
The default action of the Network ACL should be set to deny for when IPs are not matched.
Azure services can be allowed to bypass.
See https://avd.aquasec.com/misconfig/avd-azu-0013
────────────────────────────────────────
terraform/key_vault.tf:1-39
────────────────────────────────────────
1 ┌ resource "azurerm_key_vault" "main" {
2 │ # name needs to be globally unique
3 │ name = "eligibility-server-${local.env_name}"
4 │ location = data.azurerm_resource_group.main.location
5 │ resource_group_name = data.azurerm_resource_group.main.name
6 │ sku_name = "standard"
7 │ tenant_id = data.azurerm_client_config.current.tenant_id
8 │
9 └ # allow engineers to fully manage secrets
..
────────────────────────────────────────
```

From [the Azure docs](https://learn.microsoft.com/en-us/azure/key-vault/general/network-security#key-vault-firewall-enabled-private-link):

> After firewall rules are in effect, users can only perform Key Vault [data plane](https://learn.microsoft.com/en-us/azure/key-vault/general/security-features#privileged-access) operations when their requests originate from allowed virtual networks or IPv4 address ranges. This also applies to accessing Key Vault from the Azure portal. Although users can browse to a key vault from the Azure portal, they might not be able to list keys, secrets, or certificates if their client machine is not in the allowed list.

This might be a bit more annoying for engineers since we don't have an office or VPN with a known IP range, so we should consider if we just want to accept this risk.

This would apply to Benefits as well. cc https://github.com/cal-itp/benefits/issues/1153

**Comment by thekaveman** [comment]
@angela-tran to confirm access policies on Key Vault

**Comment by thekaveman** [comment]
Accepting the risk for now.
