### ISSUE TITLE
Restrict server to respond only to a list of IP addresses

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/eligibility-server#208]
### IP restrictions
This could be done via `ip_restrictions` on the App Service. See #181 for the work done so far on this.

Theoretically, we should be able to use the values from [outbound_ip_address_list](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app#outbound_ip_address_list) for the Benefits app service, but this was not working so we ended up [removing the variable value](https://github.com/cal-itp/eligibility-server/issues/189) for the initial launch.

### Front door
Do some research to see if using a [front door](https://azure.microsoft.com/en-us/products/frontdoor/) on eligibility-server would simplify the networking details for IP restriction. Also see if the Front door provides other security measures that we'd like to have.

**Comment by afeld** [comment]
Relevant docs: https://learn.microsoft.com/en-us/azure/architecture/example-scenario/service-to-service/restrict-communications

**Comment by angela-tran** [comment]
Because the [Benefits](https://github.com/cal-itp/benefits) app service integrates with a virtual network using a subnet with [service endpoints](), its requests are routed through Azure's optimized backbone, resulting in an IP address that's not in the `outbound_ip_address_list`. Here is a screenshot of one such request:

![image](https://user-images.githubusercontent.com/25497886/204927651-17db166d-051c-4a62-8ebf-4bb6e9b3629a.png)

However, when using a Front Door in front of eligibility-server, the request from Benefits comes through with an IP address listed in its outbound IP addresses, so we can use the Front Door's WAF to achieve what we want.
