### ISSUE TITLE
Define Azure DevOps configuration in code

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/eligibility-server#210]
@afeld and I created the Azure DevOps instance for MST manually. We could define this through code using the [`azuredevops` Terraform provider](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs).

The things that we created:
 - a service connection for deployment
 - a pipeline pointed at this repo's `azure-pipelines.yml` file

I also later created:
 - a pipeline for restarting the app services so that we get a nightly data-refresh

Would defining all this in Terraform actually be worth doing right now? i.e. maybe we hold off on doing this until we need to set up another DevOps instance.

**Comment by afeld** [comment]
> Would defining all this in Terraform actually be worth doing right now?

One of the benefits could be showing difference in configuration between our two Azure DevOps Organizations, in the same way that not understanding those settings/defaults [bit us with Cloudflare](https://docs.google.com/document/d/1S6KOmN-Wti9J2wUjYZpcAMmmbQddXTXdSh9xnXIA-Ow/edit#). Not saying that's enough of a reason to prioritize this over other things.

**Comment by thekaveman** [comment]
We have no plans to create another instance of the Eligibility Server.
