### ISSUE TITLE
Create Azure pipeline task for selecting workspace

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/eligibility-server#212]
In #175, @afeld wrote a Python script for the pipeline to detemine which Terraform workspace it should use based on what triggered the pipeline to run and what the source and target branches are.

We can create a [custom Azure pipeline task](https://learn.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops) to make this reusable across projects - see cal-itp/benefits#1038 for more on reusable components.

As a part of this issue, we should also consolidate the workspace selection logic from #194 which ensures that both `./init.sh` and `workspace.py` map the `prod` Git branch to the `default` Terraform workspace.

## Acceptance criteria

- [ ] There is a consistent, reliable way to manage `dev`, `test`, `prod` branch deployments

## Definition of done

- [ ] There's a drop-in Task for selecting the Terraform workspace based on the target/source branch

**Comment by afeld** [comment]
Minor: Thoughts about transferring this issue to [docker-python-web](https://github.com/cal-itp/docker-python-web), if we intend for that to be the home of reusable infrastructure components?

**Comment by afeld** [comment]
Note that [the TypeScript API has support for setting variables in the script](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/docs/azure-pipelines-task-lib.md#tasksetVariable), which could be useful.

**Comment by thekaveman** [comment]
We don't intend to refactor the infrastructure into reusable components at this time.
