### ISSUE TITLE
Decide how to configure environment-specific pipeline variables

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/eligibility-server#213]
There are cases where we would need environment-specific pipeline variables. For example, the `dev` environment might need a different list of allowed IP addresses as opposed to the ones for `test` and `prod`.

Research needs to be done on how this can be accomplished. Should we just define variables with the environment name appended? e.g. `IP_ADDRESS_WHITELIST_DEV`

**Comment by angela-tran** [comment]
Some ideas here: https://stackoverflow.com/questions/45587553/terraform-environment-specific-variables

**Comment by afeld** [comment]
Another option would be to create separate pipelines per environment, potentially using a [template](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops) across them. The solution you found of [taking the values in through a `map`](https://stackoverflow.com/a/49621326/358804) is simpler though.

**Comment by thekaveman** [comment]
We have something working right now for handling the IP address allowlists, and don't have additional use-cases for this change.
