### ISSUE TITLE
Have Terraform reference names rather than IDs, reducing the number of required variables

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/eligibility-server#215]
The idea here (I think) would be to query for resources based on their name (kind of like what Benefit's [`terraform/init.sh` is doing](https://github.com/cal-itp/benefits/blob/5d066420cca2f945d8d37557b32687e2889acfc5/terraform/init.sh#L15)). 

This would require us to have more permissions.

> Give the Group and the service principal permissions to read the lists of Applications and Groups, perhaps through a shared Terraform policy/role/something?
> 
> Maybe not worth the effort / expanded privileges

**Comment by thekaveman** [comment]
This doesn't seem worth the effort right now.
