### ISSUE TITLE
Fix SOURCE and TARGET variables for manual pipeline runs

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/eligibility-server#217]
Manual pipelines happen to work because the [default](https://github.com/cal-itp/eligibility-server/blob/dev/terraform/pipeline/workspace.py#L18-L20) is to use the `dev` Terraform workspace.

However, as shown by the statement printed during the ["Determine deployment environment" step](https://dev.azure.com/mstransit/courtesy-cards/_build/results?buildId=47&view=logs&j=bc150913-bfac-577d-ab97-4eb22da69064&t=c193f424-b810-555d-4305-c18366d00f07&l=12), the SOURCE and TARGET variables are not set correctly.

We should figure out which [Azure predefined variables](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml) to use for Manual runs.

**Comment by thekaveman** [comment]
We rarely if ever run our pipeline manually. They have changed since the time this issue was opened as well.
