### ISSUE TITLE
Create a smoke test for IP restriction

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/eligibility-server#224]
- We are allowing the availability tests through, which is good… What do we think about having a smoke test to ensure other requests are _not_ allowed? Could do this through [a GitHub Action](https://github.com/marketplace/actions/http-status) or [Azure Pipeline task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/invoke-rest-api-v1?view=azure-pipelines&tabs=yaml).

_Originally posted by @afeld in https://github.com/cal-itp/eligibility-server/pull/222#pullrequestreview-1202757343_

**Comment by thekaveman** [comment]
Doesn't seem worth the effort right now.
