### ISSUE TITLE
Fix platform for Apple hardware

### ISSUE THREAD

**Issue by afeld** [cal-itp/eligibility-server#247]
When trying to run `./bin/build.sh` on Benefits, I get the following error [while it's running `docker compose pull server`](https://github.com/cal-itp/benefits/blob/f97a4c699d815559829d9f6148d8a91f31c56f0a/bin/build.sh#L16):

```
[+] Running 0/1
 ⠹ server Pulling                                                                                   1.2s
no matching manifest for linux/arm64/v8 in the manifest list entries
```

This is apparently [because I'm running on Apple Silicon](https://stackoverflow.com/questions/65456814/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8).

[Here's the existing list of `platforms` being used.](https://github.com/cal-itp/eligibility-server/actions/runs/4116617124/jobs/7106883271#step:4:122)

A workaround is adding `platform: linux/amd64` under the `server` in the Benefits `compose.yml`. I think a more robust solution would be adding Apple Silicon [platform](https://docs.docker.com/build/building/multi-platform/) support to the Eligibility Server image, possibly [through QEMU](https://github.com/docker/setup-buildx-action#usage).

**Comment by machikoyasuda** [comment]
This bug is fixed with https://github.com/cal-itp/benefits/pull/1354

**Comment by machikoyasuda** [comment]
Fixed with https://github.com/cal-itp/benefits/issues/1357
