### ISSUE TITLE
Make ignoring of downtime more robust

### ISSUE THREAD

**Issue by afeld** [cal-itp/eligibility-server#249]
Follow-up to https://github.com/cal-itp/eligibility-server/issues/220.

Right now, there seem to be several minutes of downtime on each deploy/restart of the app. While not ideal, this is expected, and thus we probably don't want an alert when that happens. [Alert rules](https://learn.microsoft.com/en-us/azure/azure-monitor/alerts/alerts-create-new-alert-rule?tabs=metric) support conditions, so we could theoretically modify the Monitor to only alert for downtimes of over a few minutes. That would then mean the scheduled alert suppression added in https://github.com/cal-itp/eligibility-server/pull/241 could be removed.

**Comment by thekaveman** [comment]
This hasn't been an ongoing concern that we'd like to address right now.
