### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/eligibility-server#26]
To the latest version possible.

- [x] Flask, Flask-REST
- [x] jwcrypto
- [x] cryptography

**Comment by aditirao7** [comment]
Hi! I was browsing for flask related issues and came across this one, maybe a dependabot could be set up instead of manually updating the dependencies?

**Comment by thekaveman** [comment]
Great idea @aditirao7. We have a tracking issue #28 to set up automated scans. This codebase was recently [refactored out of another project](/cal-itp/benefits/issues/121) and so we need to manually upgrade dependencies and do some testing for this initial round.

**Comment by aditirao7** [comment]
@thekaveman If you want, I can setup the dependabot once you're done with testing :)
