### ISSUE TITLE
Write incident report for downtime 6/21-6/22/23

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/eligibility-server#267]
Resolved by the fix outlined in #265 and merged in #266.

See this issue for an example/template: https://github.com/cal-itp/benefits/issues/826

**Comment by angela-tran** [comment]
Here's the draft report: https://docs.google.com/document/d/1GKOM7xOxDi9Uw1j00DTnBHZGJVH7p04GJEyqMWGDgiQ/edit

**Comment by thekaveman** [comment]
This looks great, thank you! I made a few minor edits and added a bit more details around the problem and solution.

When you have a chance, can you please post a link as a reply-to-channel to [this thread](https://cal-itp.slack.com/archives/C013W8RUAMU/p1687470873420909), and let's also send a PDF copy to the email thread we started with MST IT yesterday.

**Comment by indexing** [comment]
@thekaveman We may want to include the priority we assigned for the incident (Urgent?) in the report to show our response matched our SOP.  https://docs.google.com/document/d/1qtev8qItPiTB4Tp9FQ87XsLtWZ4HlNXqoe9vF2VuGcY/edit#heading=h.enrx9qtt9lka

**Comment by angela-tran** [comment]
Closing this ticket since the report was sent out on Friday, June 23
