### ISSUE TITLE
Add support for running infra pipeline when Git tag is pushed with specific name

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/eligibility-server#284]
- [x] Decide on naming pattern for Git tags for test and prod environments

### Do in isolated testing environment
- [x] Update `azure-pipeline.yml` to be triggered by Git tag for specific naming patterns
- [x] Update logic that decides when to use `test` and prod/`default` Terraform workspaces (logic is in `workspace.py`)
- [x] Update `azure-pipeline.yml` to require approval for stage that runs `terraform apply` for test/prod deployment
   - [x] Split up pipeline into multiple stages to allow for this
   - [x] Get `terraform plan` stage to save a `tfplan` for the `apply` command to use
- [x] ~Make sure the stage that runs `terraform plan` always runs for test/prod deployment~ already works as written
- [x] Make sure the stage that runs `terraform apply` runs for tag-based test/prod deployment
- [x] Code cleanup: make the two stages share variables

Done in #307 

### Make changes to real pipeline
- [x] Update `azure-pipeline.yml` to be triggered by Git tag for specific naming patterns
- [x] Update logic that decides when to use `test` and prod/`default` Terraform workspaces (logic is in `workspace.py`)
- [x] Update `azure-pipeline.yml` to require approval for stage that runs `terraform apply` for test/prod deployment
- [x] ~Make sure the stage that runs `terraform plan` always runs for test/prod deployment~ already works as written
- [x] Make sure the stage that runs `terraform apply` runs for tag-based test/prod deployment

Done in #310

**Comment by angela-tran** [comment]
> - [ ] Update `azure-pipeline.yml` to be triggered by Git tag for specific naming patterns

Based on Azure DevOps documentation, this can be done as a ["branch" trigger that starts with `refs/tags`](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#branches) or as a [tag trigger](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#tags). There is a note under the Tags section that makes me think we might want to use the branch trigger. The note implies that a _branch_ matching the `tag` filter could trigger the pipeline (that's how I'm reading it at least), and we wouldn't want that.

> 
> Important
> 
> If you specify tags in combination with branch filters, the trigger will fire if either the branch filter is satisfied or the tag filter is satisfied. For example, if a pushed tag satisfies the branch filter, the pipeline triggers even if the tag is excluded by the tag filter, because the push satisfied the branch filter.

**Comment by angela-tran** [comment]
> The note implies that a _branch_ matching the `tag` filter could trigger the pipeline (that's how I'm reading it at least)

I was reading it incorrectly. After trying out various pipeline runs with various branch/tag names, I understand now that this means that if you tag a commit that is also the commit referenced by a branch, then if the branch name happens to satisfy a branch filter, pushing that tag would trigger the pipeline.

**Comment by angela-tran** [comment]
Updates:
 
- I've been experimenting with pipeline changes on the branch in #307

- As shared during Monday's dev standup, I noticed that my commits to that branch were triggering both the real MST DevOps pipeline as well as another DevOps pipeline I created in our separate `compilerllc` organization. This doesn't match the documentation that Kegan linked to in #294 which says that only the "first" organization's pipeline will be triggered by commits or pull requests.
 
- In an effort to isolate my experiments to just a pipeline in `compilerllc`:
   - I created a copy of the pipeline YAML file called `experiment-pipeline.yml` at the root of the project
   - Updated its path filter to `experiment-*` so that it'll only look at my file
   - Reverted the original pipeline YAML back

We installed the Terraform extension in `compilerllc` so in theory we're now ready to run Terraform tasks. I ran into a blocker just now though, where my pipeline is triggered but then says
> No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request

![image](https://github.com/cal-itp/eligibility-server/assets/25497886/7c3753dc-989c-47d0-bb38-a8f17df73486)

Googling this error, I see a [StackOverflow answer](https://stackoverflow.com/questions/68405027/how-to-resolve-no-hosted-parallelism-has-been-purchased-or-granted-in-free-tie) from July 2021 that basically says Azure made a change so that free accounts have to make a request in order to be able to run jobs.

I'm confused by this though because I don't remember us having to do that for MST's pipeline, and we created that in November 2022...

See the "Parallel jobs" settings for `compilerllc` vs. MST's:
| Compiler (0 jobs for Microsoft-hosted) | MST (1 parallel job for Microsoft-hosted) |
| --- | --- |
| ![image](https://github.com/cal-itp/eligibility-server/assets/25497886/151e2ab5-0adc-47c8-b089-8672f9e96be4) | ![image](https://github.com/cal-itp/eligibility-server/assets/25497886/b9dc56a7-6755-498c-b908-339d22f898c8) |

I filled out the [request form](https://forms.office.com/pages/responsepage.aspx?id=v4j5cvGGr0GRqy180BHbR63mUWPlq7NEsFZhkyH8jChUMlM3QzdDMFZOMkVBWU5BWFM3SDI2QlRBSC4u), and it said "it could take 2-3 business days to proceed the request."

### New plan
I'm just gonna change the pipeline in my branch to not actually run Terraform and have it run in MST's DevOps org. This will still allow me to test / figure out the correct syntax for all the tag stuff we want to add to the pipeline while ensuring my experiments don't touch anything in MST's Azure environment.

**Comment by angela-tran** [comment]
Our request was approved on 8/23/2023, and I've been able to run my pipeline in `compilerllc` yesterday and today. I replaced the terraform commands with simple echo statements to make testing easier (see [a recent pipeline run](https://dev.azure.com/compilerllc/Test%20Eligibility%20Server/_build/results?buildId=41&view=results)).

**Comment by angela-tran** [comment]
@thekaveman My next step is to put back the terraform commands and try to get the `terraform plan` stage to save a plan file that is then used by the `terraform apply` stage. This is so we can have an approval check before the `apply` stage.

To work on this though, I need:
 - a service connection between Azure DevOps and the Azure Portal
 - an Azure subscription in the "Compiler LLC" directory 

![image](https://github.com/cal-itp/eligibility-server/assets/25497886/0808c2f9-cf01-4537-9476-cad2adc6cd73)

![image](https://github.com/cal-itp/eligibility-server/assets/25497886/71894fab-7349-4eb4-a94d-60cb2110f2fe)

Once I have those, I can define a small Terraform file that just creates a Resource Group for my pipeline to run so that it isn't trying to create all the infrastructure for a new eligibility-server.

Should I go ahead and set up the subscription, or do you want to do that? The Pay-As-You-Go option requires entering payment information.
![image](https://github.com/cal-itp/eligibility-server/assets/25497886/7b29f63c-1efc-4bfb-8693-9cc6943de5c8)

**Comment by thekaveman** [comment]
@angela-tran Go for it! You can use your card for now.

**Comment by angela-tran** [comment]
Things that have to be set up manually in Azure and were done yesterday/today:
 - Subscription
 - Resource Group for holding Terraform state (`backendResourceGroupName` is needed in pipeline YAML file and in Terraform file that defines the resource provider)
 - Storage Account in that Resource Group
 - Container in that Storage Account

**Comment by angela-tran** [comment]
Something weird I've noticed yesterday and today:

There is sometimes a long delay between pushing the tag and the pipeline getting triggered.

Earlier I did the following:
 - created some commits in my branch locally (did not push to GitHub)
 - created an annotated tag called `2023.08.202-rc1` on the last commit and pushed to GitHub at 11:15am CT
 - created an annotated tag called `2023.08.202` on the last commit and pushed to GitHub at 11:17amCT
 - pushed the commits to the remote branch on GitHub, which is associated with a pull request (#307)

The pipeline triggered at 11:20am CT for the new commits on the pull request, then at 11:21am CT for the `2023.08.202` tag, and finally at **11:30am** for the `2023.08.202-rc1` tag.

![image](https://github.com/cal-itp/eligibility-server/assets/25497886/f3b4d89c-5009-4e2d-8deb-6078e356f4b5)

![image](https://github.com/cal-itp/eligibility-server/assets/25497886/2be262c6-c74c-4515-a346-a9b4d4808348)

![image](https://github.com/cal-itp/eligibility-server/assets/25497886/b3c31c3d-142a-4cc4-a4ad-07cf447d6c28)
