### ISSUE TITLE
Add support for app getting its version dynamically

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/eligibility-server#287]
May be able to use https://setuptools-git-versioning.readthedocs.io/en/stable/install.html#pyproject-toml

It'd be simplest if this can be done in a way that still works with the old deployment model in case we need to do a release while we're in the middle of working on the new deployment model (e.g. a hotfix). 

However, if this isn't compatible with our old deployment model, then we'll need to think more about when to merge this in.

**Comment by thekaveman** [comment]
We have a model of this working in the [`littlepay` repo](https://github.com/cal-itp/littlepay) that we may be able to follow:

1. Configure [`setuptools_scm`](https://setuptools-scm.readthedocs.io/en/latest/) in the [`build-system`](https://github.com/cal-itp/littlepay/blob/main/pyproject.toml#L38) and [`tool`](https://github.com/cal-itp/littlepay/blob/main/pyproject.toml#L66) sections of `pyproject.toml`
2. Configure the [`version`](https://github.com/cal-itp/littlepay/blob/main/pyproject.toml#L4) to be dynamic in `pyproject.toml`
3. Make the package [`__init__.py` read the version from the environment](https://github.com/cal-itp/littlepay/blob/main/littlepay/__init__.py#L4)
4. For the _devcontainer_, copy the `.git` directory during build time so version metadata is available

See the following commit with all of the above changes: https://github.com/cal-itp/littlepay/commit/4cf866b12992ff49300bd65ea82dd32264eee9f5
