### ISSUE TITLE
Update documentation to reflect new deployment model

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/eligibility-server#289]
At a minimum, let's update
 - [x] [release documentation](https://docs.calitp.org/eligibility-server/releases/)
 - [x] [infrastructure documentation](https://docs.calitp.org/eligibility-server/deployment/infrastructure/)

Feel free to add to the list above with other documentation that I might've missed.

~Also, maybe we should add that infrastructure documentation to the docs site?~ done in https://github.com/cal-itp/eligibility-server/issues/293

**Comment by thekaveman** [comment]
> Also, maybe we should add that infrastructure documentation to the docs site?

Definitely 👍
