### ISSUE TITLE
Fully migrate to new deployment model

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/eligibility-server#290]
- [x] Create a `main` branch, add branch protection rules similar to that of `dev`
 - [x] Rename references to `dev` branch to use `main`
 - [x] Add logic to tag `main` branch's Docker image as `dev`
 - [x] Update pipeline logic for getting deployment environment to consider `main` branch
 - [x] Remove logic for deriving Docker tag name from Git branches for test/prod
 - [x] Delete `test` and `prod` branch triggers from `azure-pipeline.yml` and `deploy.yml`
 - [x] Make `main` the default branch in the repo

## After close / merge of #414

 - [ ] Delete `dev`, `test`, and `prod` branches and branch protection rules
 - [ ] Update `main` branch protection to require the `test` check

**Comment by thekaveman** [comment]
Created `main` branch from the state of `dev` as of the most recent full deploy/release `2024.01.12`
