### ISSUE TITLE
Trigger azure-pipelines.yml via GitHub Action

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/eligibility-server#294]
This has some overlap with #284 and so will need to coordinate, possibly building on top of the work done there.

A single GitHub repository can be associated with multiple Azure DevOps organizations/projects:

> Once the GitHub App is installed, pipelines can be created for the organization's repositories in different Azure DevOps organizations and projects.

_From [Azure docs: Build GitHub repositories](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#create-pipelines-in-multiple-azure-devops-organizations-and-projects)_.

But the docs go on to say (emphasis mine):

> However, if you create pipelines for a single repository in multiple Azure DevOps organizations, **_only the first organization's pipelines can be automatically triggered by GitHub commits or pull requests_**. Manual or scheduled builds are still possible in secondary Azure DevOps organizations.

So in order to deploy to multiple Azure DevOps orgs (i.e. MST and SBMTD), we're going to need to trigger the `azure-pipelines.yml` run manually, via GitHub Actions. 

Further, (if possible) it would make sense to trigger every org's pipeline in the same way, e.g. _not_ have one of the DevOps orgs setup for "automatic trigger by GitHub commits or pull requests" like mentioned in the docs above. Each org should deploy via the GitHub Action.

Note _manually_ here does not mean literally a human clicking a button to trigger a workflow. It means we'll need a GitHub Actions workflow (that acts on e.g. tag, to accommodate what is needed for #284) that then triggers the pipeline.

**Comment by angela-tran** [comment]
This task may not be necessary based on some findings from my experiments documented in https://github.com/cal-itp/eligibility-server/issues/284#issuecomment-1688736156

**Comment by angela-tran** [comment]
Once #346 is merged in, I suggest that as our next step we set up an Azure DevOps pipeline in SBMTD's organization and see if GitHub commits / pull requests automatically trigger in both MST and SBMTD or just one. That will help us decide if we need to do this ticket or not.

**Comment by angela-tran** [comment]
I ran several experiments to help us decide if we need to do this ticket or not. In my first experiment, I made a test commit - 750d85f - on the `feat/sbmtd-infra-pipeline` branch. In my second experiment, I opened #352. Both experiments resulted in only triggering the MST pipeline.

This behavior matches what the Azure docs say. 

I'm not sure what difference was causing the behavior described in https://github.com/cal-itp/eligibility-server/issues/294#issuecomment-1734642840. You can see that both MST and Compiler LLC pipelines were being triggered by noticing that the Azure pipelines link in [#307](https://github.com/cal-itp/eligibility-server/pull/307/checks?check_run_id=16352712549) goes to `mstransit` (though the build unfortunately no longer exists) and that there is a [corresponding build in Compiler LLC](https://dev.azure.com/compilerllc/Test%20Eligibility%20Server/_build/results?buildId=108&view=results).

But anyways, the point is that our _current_ configuration behaves such that we need to do this ticket. 👍

**Comment by angela-tran** [comment]
Today we tried out merging #349 into `dev`, and it triggered a pipeline run in each organization

**Comment by thekaveman** [comment]
The pipelines do run in each org when a PR is merged :+1: 

However we only get the `plan` run for a PR being opened against `dev`, `test`, or `prod` for the first org (MST). Hence we'll still need an action workflow to at least trigger the `plan`.

**Comment by thekaveman** [comment]
Pausing for now -- we can `apply` changes to multiple orgs, which was the main goal. 

As we make more progress on #282 our thinking / procedure here may change.

**Comment by thekaveman** [comment]
This doesn't feel like it is worth the effort at this time, as the deployments for MST and SBMTD are currently working. We do not have any plans to expand Eligibility Server to additional agencies.
