### ISSUE TITLE
Make git SHA and pipdeptree available as static files

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/eligibility-server#334]
Similar to e.g. `benefits.calitp.org/static/sha.txt`, it would be nice to be able to see the SHA of the deployed version of Eligibility Server as another quick check.

See also the work in cal-itp/benefits#1733 to get the Python dependency tree available as a static file in the image.

* [ ] Need to figure out how to serve static files from Eligibility Server -- ideally we aren't creating endpoints in the app, and this can be handled by `nginx` before the request even gets to the app (like how static files work in `benefits`).

**Comment by angela-tran** [comment]
From the [Flask docs on static files](https://flask.palletsprojects.com/en/2.3.x/tutorial/static/), it is as simple as having a file in the `/static` directory.

I tested it out by creating a file at `eligibility_server/static/sha.txt` and launching the Flask app. I was able to see the file at `<url>/static/sha.txt` 🙂
