### ISSUE TITLE
Configure Azure firewall to allow requests to static files

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/eligibility-server#337]
This is a follow-up to #334. 

We added two static files to our app with #335 and #336; however, our Azure firewall configuration does not give public access to those files.

We should update the firewall's custom rules to allow us to access those files.

**Comment by angela-tran** [comment]
Maybe the simplest solution is to rename the rule from `healthcheck` to `public_access` or something, and then add match rules for either the static directory or the specific static files.

**Comment by thekaveman** [comment]
@angela-tran That sounds great, I like that solution 👍

**Comment by angela-tran** [comment]
> @angela-tran That sounds great, I like that solution 👍
> 
> > add match conditions for either the static directory or the specific static files.
> 
> Shouldn't a match condition for the directory suffice? I wouldn't want to have to maintain a list of files here as well, if we can avoid that.

Yeah, if we can do it for the static directory, I think that'd be preferred. I think we can do that using the [`BeginsWith` operator](https://learn.microsoft.com/en-us/azure/web-application-firewall/afds/waf-front-door-custom-rules#priority-action-types-and-match-conditions)
