### ISSUE TITLE
Key Vault name needs to be globally unique

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/eligibility-server#353]
Follow-up to #349 

From https://dev.azure.com/sbmtd/eligibility-server/_build/results?buildId=12&view=logs&j=de9ad78b-21c3-52d3-f75b-ac0998b9a9c9&t=9f0d2323-8cb9-5ca6-9fa8-c6837cb4c41d

> ╷
> │ `Error: creating Vault: (Name "eligibility-server-dev" / Resource Group "sbmtd-mobility-pass-eligibility-dev"): keyvault.VaultsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="VaultAlreadyExists" Message="The vault name 'eligibility-server-dev' is already in use. Vault names are globally unique so it is possible that the name is already taken. If you are sure that the vault name was not taken then it is possible that a vault with the same name was recently deleted but not purged after being placed in a recoverable state. If the vault is in a recoverable state then the vault will need to be purged before reusing the name. For more information about VaultAlreadyExists, soft delete and purging a vault follow this link [https://go.microsoft.com/fwlink/?linkid=2147740."](https://go.microsoft.com/fwlink/?linkid=2147740.%22)`
> │ 
> │   with azurerm_key_vault.main,
> │   on key_vault.tf line 1, in resource "azurerm_key_vault" "main":
> │    1: resource "azurerm_key_vault" "main" {
> │ 
> ╵

Here are the Resource naming restrictions for Azure Key Vaults: https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftkeyvault

> Length: 3-24
> 
> Valid characters:
> Alphanumerics and hyphens.
> Start with letter. End with letter or digit. Can't contain consecutive hyphens.

**Comment by thekaveman** [comment]
> creating Vault: (Name "eligibility-server-dev"...

Was this an error on our part? Why isn't SBMTD a part of this name?

**Comment by angela-tran** [comment]
> Was this an error on our part? Why isn't SBMTD a part of this name? Or we just didn't know they had to be globally unique and thought we could create them under the RG?

Yeah, we thought we could create them under the RG because the existing name didn't have anything agency-specific.
