### ISSUE TITLE
Remove Azure pipeline approval requirement

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/eligibility-server#370]
Our Azure DevOps pipeline requires approval for the `terraform apply` stage. 

We added this as part of the refactor towards tag-based deployment. In practice, all engineers are almost always on a call doing the release together, and this approval stage hasn't been necessary or useful.

Let's remove it entirely.

**Comment by angela-tran** [comment]
I was able to install the Azure Pipelines app into Cal-ITP Slack. I signed in to it using my Azure DevOps account. Entering `/azpipelines subscribe [pipeline url]` gave me back a message of `Configuration failed. Please make sure that the organization '*****' exists and that you have sufficient permissions.` (***** is where the org name is)

Found from [Azure DevOps docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/integrations/slack?view=azure-devops) that:
> For Azure DevOps, you need to be in the Project Collection Administrators or Project Administrators group to set up a Slack subscription.

**Comment by thekaveman** [comment]
We decided that the pipeline approvals aren't necessary, and removing them will represent a quality of life improvement for engineers. Rewrote this ticket to reflect that.

**Comment by angela-tran** [comment]
Follow-up needed: #480
