### ISSUE TITLE
Fix release-tag trigger in infra pipeline definition files

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/eligibility-server#377]
The glob pattern we're using for release tags in `azure-pipelines.yml` is too permissive - `20??.??.?*` matches more than just release tags. 

We should update our trigger pattern in [MST's pipeline](https://github.com/cal-itp/eligibility-server/blob/dev/terraform/mst/azure-pipelines.yml#L10) and [SBMTD's pipeline](https://github.com/cal-itp/eligibility-server/blob/dev/terraform/sbmtd/azure-pipelines.yml#L10).

_Originally posted by @angela-tran in https://github.com/cal-itp/eligibility-server/issues/286#issuecomment-1839253574_

**Comment by thekaveman** [comment]
This consequences of this are relatively minor, we can always create new tags at the correct SHA as-needed.
