### ISSUE TITLE
Version and release strategy

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/eligibility-server#48]
Tracking a todo in this repository based on a number of related issues:

* cal-itp/benefits#179
* cal-itp/benefits#180
* cal-itp/hashfields#10

We currently push the server image tagged with `main` to GHCR for every commit to the `main` branch, and tagged with the commit SHA and `latest` for every Release.

As we're seeing elsewhere, a more structured version/release strategy could help bring clarity to the codebase. We should pick a strategy here that aligns across the Benefits portfolio (as in the linked issues).

**Comment by vykster** [comment]
Placeholder to remind the team that this repo needs to be versioned the same way the others are.

**Comment by vykster** [comment]
New issue #59
